config/routes.rb
# In config/routes.rb
Rails.application.routes.draw do
  # constraints(subdomain: /.+/) do
    namespace :tenants do
      root to: 'blog_posts#index'  # Set the root route for tenants
      resources :blog_posts do
        member do
          get :version_history # Add this line
        end
      end
    end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :tenant
  has_many :blog_posts
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :title, presence: true
  belongs_to :user # author
  belongs_to :blog
  has_many :comments
  has_many :versions
  has_many :blog_post_tags
  has_many :tags, through: :blog_post_tags
  after_save :create_version

  private

  def create_version
    versions.create(content: content, user: user) if content_changed?
  end
end

app/models/blog_post_tag.rb
class BlogPostTag < ApplicationRecord
  belongs_to :blog_post
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :user
  belongs_to :blog_post
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :tenant
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :blog_post_tags
  has_many :blog_posts, through: :blog_post_tags
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_many :users
  has_many :blogs
  has_many :subscriptions
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password # for password hashing

  belongs_to :tenant
  has_many :blog_posts
  has_many :comments
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :subscriptions

  enum role: { admin: 0, author: 1, reader: 2 }

  validates :email, presence: true, uniqueness: { scope: :tenant_id }
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
  belongs_to :tenant
end

app/models/version.rb
class Version < ApplicationRecord
  belongs_to :blog_post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_tenant

  private

  def set_current_tenant
    @current_tenant = Tenant.find_by(subdomain: request.subdomain) || Tenant.first
    # if @current_tenant.nil?
    #   redirect_to tenants_root_url, alert: 'Tenant not found' # Use tenants_root_url
    # end
  end
end

app/controllers/tenants/blog_posts_controller.rb
# app/controllers/tenants/blog_posts_controller.rb
module Tenants
  class BlogPostsController < ApplicationController
    before_action :set_blog_post, only: %i[show edit update destroy]

    def index
      @blog_posts = BlogPost.joins(blog: :tenant).where(blogs: { tenant_id: 7})
    end

    def new
      @blog_post = @current_tenant.blogs.new
    end
    
    def version_history
      @blog_post = BlogPost.find(params[:id])
      @versions = @blog_post.versions
    end

    def create
      @blog_post = @current_tenant.blogs.new(blog_post_params)
      @blog_post.user = current_user
      if @blog_post.save
        redirect_to @blog_post, notice: 'Blog post was successfully created.'
      else
        render :new
      end
    end

    private

    def set_blog_post
      @blog_post = @current_tenant.blogs.find(params[:id])
    end

    def blog_post_params
      params.require(:blog_post).permit(:title, :content)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTenentApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/tenant.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @current_tenant.name %> Blog Platform</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Welcome to <%= @current_tenant.name %> Blogging Platform</h1>
      <%= link_to 'Logout', logout_path, method: :delete %>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer>
      <p>&copy; <%= Time.current.year %> - Multi-Tenant Blog Platform</p>
    </footer>
  </body>
</html>

app/views/tenants/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= form_with(model: @blog_post, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content, rows: 10 %>
  </div>

  <div>
    <%= form.submit 'Update Blog Post' %>
  </div>
<% end %>

<%= link_to 'Back to Blog Posts', blog_posts_path %>

app/views/tenants/blog_posts/index.html.erb
<h1>Blog Posts for <%= @current_tenant.name %></h1>

<%= link_to 'New Blog Post', new_tenants_blog_post_path %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @blog_posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, tenants_blog_post_path(post) %></td>
        <td><%= post.user.name %></td>
        <td>
          <%= link_to 'Edit', edit_tenants_blog_post_path(post) %> |
          <%= link_to 'Delete', tenants_blog_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
          <%= link_to 'View Version History', version_history_tenants_blog_post_path(post) %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tenants/blog_posts/new.html.erb
<h1>Create New Blog Post</h1>

<%= form_with(model: @tenants_blog_post, local: true) do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content %>
    <%= form.text_area :content, rows: 10 %>
  </div>

  <div>
    <%= form.submit 'Create Blog Post' %>
  </div>
<% end %>

<%= link_to 'Back to Blog Posts', tenants_blog_posts_path %>

app/views/tenants/blog_posts/show.html.erb
<h1><%= @blog_post.title %></h1>

<p>Written by: <%= @blog_post.user.name %></p>
<p><%= @blog_post.content %></p>

<hr>
<%= link_to 'Edit', edit_tenants_blog_post_path(@blog_post) %> |
<%= link_to 'Back to Blog Posts', blog_posts_path %>
<%= link_to 'View Version History', version_history_tenants_blog_post_path(@blog_post) %> 

app/views/tenants/blog_posts/version_history.html.erb
<h1>Version History for "<%= @blog_post.title %>"</h1>

<table>
  <thead>
    <tr>
      <th>Version</th>
      <th>Content</th>
      <th>Updated By</th>
      <th>Updated At</th>
    </tr>
  </thead>
  <tbody>
    <% @versions.each_with_index do |version, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= version.content %></td>
        <td><%= version.created_at.strftime("%Y-%m-%d %H:%M") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back to Blog Post', tenants_blog_post_path(@blog_post) %>